name: Build and release aarch64 binaries

on: [push]

jobs:
  release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["aarch64"]
        os: ["ubuntu18.04", "ubuntu20.04", "ubuntu22.04", "alpine"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          platforms: linux/arm64
          tags: lablup/backend.ai-hook:latest

      - name: Build libbaihook
        run: |
          docker run --rm -v "$(pwd)" lablup/backend.ai-hook:latest /bin/bash -c "./build.sh ${{ matrix.os }}"

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            ./*.so
