name: Build and release

on: [push]

jobs:
  release:
    if: contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["x86_64", "aarch64"]
        os: ["ubuntu18.04", "ubuntu20.04", "ubuntu22.04", "alpine"]
    steps:
      - uses: actions/checkout@v4

      - name: Install QEMU
        if: matrix.target == 'aarch64'
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
          sudo update-binfmts --enable qemu-aarch64

      - name: Build libbaihook
        run: |
          ./build.sh --arch ${{ matrix.target }} ${{ matrix.os }}

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            ./*.so
